name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Xcode version
        run: xcodebuild -version | cat

      - name: Check API key presence
        id: check_key
        run: |
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "OPENAI_API_KEY missing";
            echo "has_key=false" >> $GITHUB_OUTPUT;
          else
            echo "OPENAI_API_KEY set";
            echo "has_key=true" >> $GITHUB_OUTPUT;
          fi

      - name: Build and Test (unit)
        run: xcodebuild clean build test -workspace "CountryGuru.xcworkspace" -scheme "CountryGuruCITests" -configuration Debug CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPhone 16" ONLY_ACTIVE_ARCH=YES | cat

      - name: Run Integration Tests (PR to main)
        if: github.event_name == 'pull_request' && github.base_ref == 'main' && steps.check_key.outputs.has_key == 'true'
        run: |
          cd CountryGuruCore
          xcodebuild -scheme CountryGuruCoreIntegrationTests \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -only-testing:CountryGuruCoreIntegrationTests \
            test | cat
