name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and Test
        run: xcodebuild clean build test -workspace "CountryGuru.xcworkspace" -scheme "CountryGuruCITests" -configuration Debug CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,name=iPhone 16" ONLY_ACTIVE_ARCH=YES | cat
